# Generated by Django 5.1 on 2024-08-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_producto_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
